# SwiftLint Configuration for Trace
# https://realm.github.io/SwiftLint/ :contentReference[oaicite:3]{index=3}

excluded:
  - Pods
  - build
  - .build
  - DerivedData
  - TraceTests
  - TraceUITests

# Analyzer rules are opt-in in SwiftLint. :contentReference[oaicite:4]{index=4}
analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - closure_spacing
  - contains_over_first_not_nil
  - fallthrough
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_parameters
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - line_length               # SwiftUI can be legitimately long
  - function_body_length      # SwiftUI views can be long
  - type_body_length          # SwiftUI views can be long
  - file_length               # Some files naturally grow large
  - multiple_closures_with_trailing_closure # Noisy with SwiftUI APIs

# Rule configurations
identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - id
    - URL
    - url

type_name:
  min_length: 3
  max_length: 60

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

reporter: "xcode"
